### ISSUE TITLE
Why do you use r3live++ for estimating the camera’s poses in application-2?

### ISSUE THREAD

**Issue by Neo-cyber-hubb** [hku-mars/ImMesh#8]
It is an excellent work. I have read your paper ImMesh_v1.pdf. I have a question. ImMesh has its own localization module for estimating the lidar's poses. It could get the camera's poses via the lidar's poses and the extrinsic parameters between the camera and the lidar. So, why do you use r3live++ for estimating the camera’s poses in application-2? Is it because the lidar and camera is not time synchronization or other reasons?  Looking forward to your reply.

**Comment by ziv-lin** [comment]
Regarding your question, you are correct that ImMesh has its own localization module for estimating the lidar's poses.

However, In application-2, we used r3live++ for estimating the camera's poses since:
1) In most real-world applications, the lidar and camera may not be synchronized in time,  and might not be calibrated well.
2) For the time-synchronized sensor set, the camera needs to take time to expose an image properly. But the timestamp is given by the start (or end) of the frame, leading to an unknown time-offset error.

By considering these aspects, we can use the vio subsystem of 
 r3live++ for online calibrating both the spatial and temporal extrinsic.

**Comment by Neo-cyber-hubb** [comment]
Oh~I get it. Thanks for your reply!

**Comment by Neo-cyber-hubb** [comment]
Oh~I get it. Thanks for your reply!
